export const API_URL = 'https://manuais-hp.onrender.com/chat';

export const AI_PROVIDERS = [
  { id: 'gemini', label: 'Gemini (Google)',    sub: 'Google · Gemini' },
  { id: 'claude', label: 'Claude (Anthropic)', sub: 'Anthropic · Claude' },
];
export const DEFAULT_PROVIDER = 'gemini';

export const USER_MODES = {
  user: {
    id: 'user',
    label: 'Usuario',
    icon: '👤',
    color: '#00d4aa',
    description: 'Respostas simples e diretas',
    promptSuffix: 'Responda de forma simples e clara para um usuario leigo.',
  },
  tech: {
    id: 'tech',
    label: 'Tecnico',
    icon: '🔧',
    color: '#0096ff',
    description: 'Informacoes tecnicas completas',
    promptSuffix: 'Responda com detalhes tecnicos, codigos e procedimentos completos.',
  },
};

// ─── HP ───────────────────────────────────────────────────────────────────────
export const MANUALS = [
  {
    id: 'mfpe52645',
    brand: 'hp',
    label: 'MFP E52645',
    subtitle: 'HP LaserJet Managed',
    color: '#0096ff',
    indexKey: 'e52645_guia',
    searchKeys: ['e52645_guia', 'cpmd', 'service'],
    tags: ['E52645', 'MFP', 'Gerenciado'],
    topics: {
      user: {
        'Uso Diario': [
          'Como colocar papel na impressora?',
          'Como imprimir dos dois lados?',
          'Como digitalizar um documento?',
          'O papel atolou, o que faco?',
          'A impressora nao liga',
          'Impressao saindo borrada ou clara',
        ],
        'Suprimentos': [
          'Como trocar o cartucho de toner?',
          'A impressora diz que o toner esta baixo',
          'Como repor grampos?',
          'Qual cartucho usar nesta impressora?',
        ],
        'Conexao': [
          'Como conectar a impressora ao Wi-Fi?',
          'Nao consigo imprimir do celular',
          'Como configurar impressao por e-mail?',
          'Como acessar as configuracoes da impressora?',
        ],
        'Erros': [
          'O que significa esse erro na tela?',
          'Mensagem de cartucho incorreto',
          'Impressora mostra Checking engine',
          'Fax nao funciona',
        ],
      },
      tech: {
        'Operacao': [
          'Configurar bandejas de papel',
          'Impressao frente e verso duplex',
          'Digitalizar para pasta de rede SMB',
          'Configurar Quick Sets',
        ],
        'Suprimentos': [
          'Substituir cartucho de toner',
          'Numero de peca do cartucho E52645',
          'Substituir kit de manutencao',
          'Cartucho de grampos part number',
        ],
        'Rede': [
          'Configurar endereco IP estatico',
          'Acessar EWS Servidor Web Incorporado',
          'Configurar LDAP autenticacao',
          'Protocolo IPSec certificados',
        ],
        'Service': [
          'Codigos de erro painel de controle',
          'Procedimento de calibracao do scanner',
          'Substituir fusor E52645',
          'Diagnostico motor principal',
        ],
      },
    },
    prompts: {
      user: 'Voce e um assistente de suporte para usuarios da HP LaserJet Managed MFP E52645. Baseie a resposta nos TRECHOS DO MANUAL fornecidos, de forma clara e completa o suficiente para o usuario resolver o problema passo a passo. Apresente o defeito, as causas e a solucao quando os trechos trouxerem. Nao invente informacoes. Pode acrescentar orientacoes gerais verdadeiras marcando como (Complemento). Se o manual nao tiver a resposta, informe isso. Portugues Brasileiro.',
      tech: 'Voce e um tecnico especialista na HP LaserJet Managed MFP E52645. Baseie sua resposta nos TRECHOS DO MANUAL fornecidos e apresente TODAS as informacoes relevantes deles — nao resuma demais. Quando os trechos descreverem um codigo de erro, organize em: Defeito (descricao), Possiveis causas, Solucao (passo a passo) e Pecas/part numbers quando houver. Pode acrescentar conhecimento tecnico adicional APENAS se for verdadeiro e diretamente relacionado, marcando como (Complemento). NUNCA invente codigos, part numbers, valores ou procedimentos que nao estejam nos trechos. Se os trechos nao trouxerem a solucao completa, apresente o que existe e informe que o restante deve ser consultado no service manual fisico. Portugues Brasileiro.',
    },
  },
  {
    id: 'mfpe62655',
    brand: 'hp',
    label: 'MFP E62655',
    subtitle: 'HP LaserJet Managed',
    color: '#0096ff',
    indexKey: 'e62655_guia',
    searchKeys: ['e62655_guia', 'e62655_service', 'e62655_cpmd'],
    tags: ['E62655', 'MFP', 'Gerenciado'],
    topics: {
      user: {
        'Uso Diario': [
          'Como colocar papel na impressora?',
          'Como imprimir dos dois lados?',
          'Como digitalizar um documento?',
          'O papel atolou, o que faco?',
          'A impressora nao liga',
          'Impressao saindo borrada ou clara',
        ],
        'Suprimentos': [
          'Como trocar o cartucho de toner?',
          'A impressora diz que o toner esta baixo',
          'Como repor grampos?',
          'Qual cartucho usar nesta impressora?',
        ],
        'Conexao': [
          'Como conectar a impressora ao Wi-Fi?',
          'Nao consigo imprimir do celular',
          'Como configurar impressao por e-mail?',
          'Como acessar as configuracoes da impressora?',
        ],
        'Erros': [
          'O que significa esse erro na tela?',
          'Mensagem de cartucho incorreto',
          'Impressora mostra Checking engine',
          'Fax nao funciona',
        ],
      },
      tech: {
        'Operacao': [
          'Configurar bandejas de papel',
          'Impressao frente e verso duplex',
          'Digitalizar para pasta de rede SMB',
          'Configurar Quick Sets',
        ],
        'Suprimentos': [
          'Substituir cartucho de toner',
          'Numero de peca do cartucho E62655',
          'Substituir kit de manutencao',
          'Cartucho de grampos part number',
        ],
        'Rede': [
          'Configurar endereco IP estatico',
          'Acessar EWS Servidor Web Incorporado',
          'Configurar LDAP autenticacao',
          'Protocolo IPSec certificados',
        ],
        'Service': [
          'Codigos de erro painel de controle',
          'Procedimento de calibracao do scanner',
          'Substituir fusor E62655',
          'Diagnostico motor principal',
        ],
      },
    },
    prompts: {
      user: 'Voce e um assistente de suporte para usuarios da HP LaserJet Managed MFP E62655. Baseie a resposta nos TRECHOS DO MANUAL fornecidos, de forma clara e completa o suficiente para o usuario resolver o problema passo a passo. Apresente o defeito, as causas e a solucao quando os trechos trouxerem. Nao invente informacoes. Pode acrescentar orientacoes gerais verdadeiras marcando como (Complemento). Se o manual nao tiver a resposta, informe isso. Portugues Brasileiro.',
      tech: 'Voce e um tecnico especialista na HP LaserJet Managed MFP E62655. Baseie sua resposta nos TRECHOS DO MANUAL fornecidos e apresente TODAS as informacoes relevantes deles — nao resuma demais. Quando os trechos descreverem um codigo de erro, organize em: Defeito (descricao), Possiveis causas, Solucao (passo a passo) e Pecas/part numbers quando houver. Pode acrescentar conhecimento tecnico adicional APENAS se for verdadeiro e diretamente relacionado, marcando como (Complemento). NUNCA invente codigos, part numbers, valores ou procedimentos que nao estejam nos trechos. Se os trechos nao trouxerem a solucao completa, apresente o que existe e informe que o restante deve ser consultado no service manual fisico. Portugues Brasileiro.',
    },
  },
];

// ─── RICOH ────────────────────────────────────────────────────────────────────
// HP E826 Series
export const MANUALS_E826 = [
  {
    id: 'hp_e826',
    brand: 'hp',
    label: 'E826 Series',
    subtitle: 'HP LaserJet Managed MFP A3',
    color: '#0096ff',
    indexKey: 'hp_e826_guia',
    searchKeys: ['hp_e826_guia', 'hp_e826_service', 'hp_e826_cpmd'],
    tags: ['E82650', 'E82660', 'E82670', 'A3', 'Mono', 'MFP', 'FutureSmart'],
    topics: {
      user: {
        'Uso Diario': [
          'Como colocar papel na E826?',
          'Como imprimir frente e verso?',
          'Como digitalizar um documento?',
          'O papel atolou, o que faco?',
          'Como trocar o toner?',
          'Impressao saindo clara ou manchada',
        ],
        'Suprimentos': [
          'Como substituir o cartucho de toner?',
          'A impressora diz que o toner esta baixo',
          'Como trocar o TCU?',
          'Qual suprimento usar na E826?',
        ],
        'Conexao': [
          'Como acessar o EWS?',
          'Como configurar scan to email?',
          'Como configurar pasta de rede?',
          'Como definir IP estatico?',
        ],
        'Manutencao': [
          'Como limpar atolamento na porta direita?',
          'Como substituir o fusor?',
          'Como trocar rolos de bandeja?',
          'Onde consultar pecas da E826?',
        ],
      },
      tech: {
        'Operacao': [
          'Configurar bandejas A3 e A4',
          'Impressao duplex',
          'Digitalizar para email',
          'Digitalizar para pasta SMB',
        ],
        'Suprimentos': [
          'Substituir toner preto',
          'Substituir unidade de imagem',
          'Substituir TCU',
          'Consultar part numbers no parts catalog',
        ],
        'Rede': [
          'Acessar EWS Servidor Web Incorporado',
          'Configurar endereco IP estatico',
          'Configurar SMTP',
          'Configurar LDAP autenticacao',
        ],
        'Service': [
          'Procedimento de troca de fusor',
          'Limpar atolamento na area do fusor',
          'Substituir rolos de alimentacao',
          'Diagnostico de motores e sensores',
        ],
      },
    },
    prompts: {
      user: 'Voce e um assistente de suporte para usuarios da serie HP LaserJet Managed MFP E82650/E82660/E82670. Baseie a resposta nos TRECHOS DO MANUAL fornecidos, de forma clara e completa o suficiente para o usuario resolver o problema passo a passo. Apresente o defeito, as causas e a solucao quando os trechos trouxerem. Nao invente informacoes. Pode acrescentar orientacoes gerais verdadeiras marcando como (Complemento). Se o manual nao tiver a resposta, informe isso. Portugues Brasileiro.',
      tech: 'Voce e um tecnico especialista na serie HP LaserJet Managed MFP E82650/E82660/E82670, A3 monocromatica FutureSmart. Baseie sua resposta nos TRECHOS DO MANUAL fornecidos e apresente TODAS as informacoes relevantes deles - nao resuma demais. Organize o diagnostico em: Defeito ou condicao, Possiveis causas, Solucao passo a passo e Pecas/part numbers quando houver. Pode acrescentar conhecimento tecnico adicional APENAS se for verdadeiro e diretamente relacionado, marcando como (Complemento). NUNCA invente codigos, part numbers, valores ou procedimentos que nao estejam nos trechos. Se os trechos nao trouxerem a solucao completa, apresente o que existe e informe que o restante deve ser consultado no service manual fisico. Portugues Brasileiro.',
    },
  },
];

// Ricoh
export const MANUALS_RICOH = [
  {
    id: 'ricoh_imc3000',
    brand: 'ricoh',
    label: 'IM C3000/3500',
    subtitle: 'Ricoh IM C Series',
    color: '#e63946',
    indexKey: 'ricoh_imc3000_guia',
    searchKeys: ['ricoh_imc3000_service', 'ricoh_imc3000_guia', 'ricoh_imc3000_parts'],
    tags: ['IM C3000', 'IM C3500', 'Color MFP'],
    topics: {
      user: {
        'Uso Diario': [
          'Como colocar papel na impressora Ricoh?',
          'Como imprimir dos dois lados?',
          'Como digitalizar um documento?',
          'O papel atolou, o que faco?',
          'A impressora nao liga',
          'Impressao saindo com qualidade ruim',
        ],
        'Suprimentos': [
          'Como trocar o toner da Ricoh?',
          'Qual toner usar na IM C3000?',
          'Como trocar o kit de manutencao?',
          'Unidade de transferencia esta no fim',
        ],
        'Conexao': [
          'Como conectar ao Wi-Fi?',
          'Nao consigo imprimir da rede',
          'Como configurar digitalizar para email?',
          'Como acessar as configuracoes web?',
        ],
        'Erros': [
          'O que significa o codigo de erro?',
          'Mensagem de toner incorreto',
          'Erro de temperatura no fusor',
          'Scanner nao funciona',
        ],
      },
      tech: {
        'Operacao': [
          'Configurar bandejas de papel',
          'Impressao frente e verso duplex',
          'Digitalizar para pasta SMB',
          'Configurar perfis de digitalizacao',
        ],
        'Suprimentos': [
          'Substituir cartucho de toner CMYK',
          'Part number toner IM C3000/3500',
          'Substituir unidade de tambor',
          'Kit de manutencao intervalo',
        ],
        'Rede': [
          'Configurar IP estatico',
          'Acessar Web Image Monitor',
          'Configurar autenticacao LDAP',
          'Protocolo SSL/TLS certificados',
        ],
        'Service': [
          'Codigos SC (Service Call)',
          'Calibracao de cores',
          'Substituir fusor IM C3000',
          'Diagnostico do motor',
        ],
      },
    },
    prompts: {
      user: 'Voce e um assistente de suporte para usuarios de impressoras Ricoh IM C3000/3500. Baseie a resposta nos TRECHOS DO MANUAL fornecidos, de forma clara e completa o suficiente para o usuario resolver o problema passo a passo. Apresente o defeito, as causas e a solucao quando os trechos trouxerem. Nao invente informacoes. Pode acrescentar orientacoes gerais verdadeiras marcando como (Complemento). Se o manual nao tiver a resposta, informe isso. Portugues Brasileiro.',
      tech: 'Voce e um tecnico especialista em Ricoh IM C3000/3500. Baseie sua resposta nos TRECHOS DO MANUAL fornecidos e apresente TODAS as informacoes relevantes deles — nao resuma demais. Quando os trechos descreverem um codigo SC, organize em: Defeito (descricao/condicao), Possiveis causas, Solucao (passo a passo) e SPs/Pecas/part numbers quando houver. Pode acrescentar conhecimento tecnico adicional APENAS se for verdadeiro e diretamente relacionado, marcando como (Complemento). NUNCA invente codigos SC, valores de SP, tensoes, part numbers ou procedimentos que nao estejam nos trechos. Se os trechos nao trouxerem a solucao completa, apresente o que existe e informe que o restante deve ser consultado no service manual fisico. Portugues Brasileiro.',
    },
  },
  {
    id: 'ricoh_mpc3004',
    brand: 'ricoh',
    label: 'MP C3004/3504',
    subtitle: 'Ricoh MP C Series',
    color: '#e63946',
    indexKey: 'ricoh_mpc3004_guia',
    searchKeys: ['ricoh_mpc3004_service', 'ricoh_mpc3004_guia'],
    tags: ['MP C3004', 'MP C3504', 'MP C4504', 'Color MFP'],
    topics: {
      user: {
        'Uso Diario': [
          'Como colocar papel na impressora Ricoh?',
          'Como imprimir dos dois lados?',
          'Como digitalizar um documento?',
          'O papel atolou, o que faco?',
          'A impressora nao liga',
          'Impressao saindo com qualidade ruim',
        ],
        'Suprimentos': [
          'Como trocar o toner da Ricoh?',
          'Qual toner usar na MP C3004/3504?',
          'Como trocar o kit de manutencao?',
          'Unidade de transferencia esta no fim',
        ],
        'Conexao': [
          'Como conectar ao Wi-Fi?',
          'Nao consigo imprimir da rede',
          'Como configurar digitalizar para email?',
          'Como acessar as configuracoes web?',
        ],
        'Erros': [
          'O que significa o codigo de erro SC?',
          'Mensagem de toner incorreto',
          'Erro de temperatura no fusor',
          'Scanner nao funciona',
        ],
      },
      tech: {
        'Operacao': [
          'Configurar bandejas de papel',
          'Impressao frente e verso duplex',
          'Digitalizar para pasta SMB',
          'Configurar perfis de digitalizacao',
        ],
        'Suprimentos': [
          'Substituir cartucho de toner CMYK',
          'Part number toner MP C3004/3504',
          'Substituir unidade de tambor',
          'Kit de manutencao intervalo',
        ],
        'Rede': [
          'Configurar IP estatico',
          'Acessar Web Image Monitor',
          'Configurar autenticacao LDAP',
          'Protocolo SSL/TLS certificados',
        ],
        'Service': [
          'Codigos SC (Service Call)',
          'Calibracao de cores',
          'Substituir fusor MP C3004/3504',
          'Diagnostico do motor',
        ],
      },
    },
    prompts: {
      user: 'Voce e um assistente de suporte para usuarios de impressoras Ricoh MP C3004/3504. Baseie a resposta nos TRECHOS DO MANUAL fornecidos, de forma clara e completa o suficiente para o usuario resolver o problema passo a passo. Apresente o defeito, as causas e a solucao quando os trechos trouxerem. Nao invente informacoes. Pode acrescentar orientacoes gerais verdadeiras marcando como (Complemento). Se o manual nao tiver a resposta, informe isso. Portugues Brasileiro.',
      tech: 'Voce e um tecnico especialista em Ricoh MP C3004/3504. Baseie sua resposta nos TRECHOS DO MANUAL fornecidos e apresente TODAS as informacoes relevantes deles — nao resuma demais. Quando os trechos descreverem um codigo SC, organize em: Defeito (descricao/condicao), Possiveis causas, Solucao (passo a passo) e SPs/Pecas/part numbers quando houver. Pode acrescentar conhecimento tecnico adicional APENAS se for verdadeiro e diretamente relacionado, marcando como (Complemento). NUNCA invente codigos SC, valores de SP, tensoes, part numbers ou procedimentos que nao estejam nos trechos. Se os trechos nao trouxerem a solucao completa, apresente o que existe e informe que o restante deve ser consultado no service manual fisico. Portugues Brasileiro.',
    },
  },
  {
    id: 'ricoh_sp3710',
    brand: 'ricoh',
    label: 'SP 3710DN/SF',
    subtitle: 'Ricoh SP Series - Desktop Mono',
    color: '#e63946',
    indexKey: 'ricoh_sp3710_guia',
    searchKeys: ['ricoh_sp3710_service', 'ricoh_sp3710_guia', 'ricoh_sp3710_psg'],
    tags: ['SP 3710DN', 'SP 3710SF', 'Desktop', 'Mono', 'MFP'],
    topics: {
      user: {
        'Uso Diario': [
          'Como colocar papel na Ricoh SP 3710?',
          'Como imprimir dos dois lados?',
          'Como digitalizar um documento na SP 3710SF?',
          'O papel atolou, o que faco?',
          'A impressora nao liga',
          'Impressao saindo com qualidade ruim',
        ],
        'Suprimentos': [
          'Como trocar o cartucho de impressao?',
          'Qual cartucho usar na SP 3710?',
          'Como verificar o nivel do toner?',
          'Qual o rendimento do cartucho SP 3710X?',
        ],
        'Conexao': [
          'Como conectar a impressora na rede?',
          'Nao consigo imprimir da rede',
          'Como configurar digitalizar para email na SP 3710SF?',
          'Como acessar as configuracoes web?',
        ],
        'Mensagens': [
          'O que significa a mensagem no painel?',
          'Mensagem de toner baixo',
          'Erro de alimentacao de papel',
          'Scanner nao funciona na SP 3710SF',
        ],
      },
      tech: {
        'Operacao': [
          'Configurar bandejas e tipos de papel',
          'Configurar impressao duplex',
          'Digitalizar para pasta ou email na SP 3710SF',
          'Configurar funcoes de copia na SP 3710SF',
        ],
        'Suprimentos': [
          'Substituir cartucho de impressao SP 3710X',
          'Rendimento e codigo EDP do cartucho',
          'Limpeza e manutencao preventiva',
          'Diagnosticar falhas de qualidade de impressao',
        ],
        'Rede': [
          'Configurar endereco IP',
          'Acessar Web Image Monitor',
          'Configurar protocolos de rede',
          'Configurar digitalizacao em rede na SP 3710SF',
        ],
        'Service': [
          'Procedimentos de diagnostico e reparo',
          'Substituir unidade de fusao',
          'Diagnosticar alimentacao de papel',
          'Testes de entrada e saida',
        ],
      },
    },
    prompts: {
      user: 'Voce e um assistente de suporte para usuarios da serie Ricoh SP 3710DN/SF. Baseie a resposta nos TRECHOS DO MANUAL fornecidos, de forma clara e completa o suficiente para o usuario resolver o problema passo a passo. Considere que a SP 3710DN e impressora e a SP 3710SF inclui funcoes de copia, digitalizacao e fax. Apresente o defeito, as causas e a solucao quando os trechos trouxerem. Nao invente informacoes. Pode acrescentar orientacoes gerais verdadeiras marcando como (Complemento). Se o manual nao tiver a resposta, informe isso. Portugues Brasileiro.',
      tech: 'Voce e um tecnico especialista na serie Ricoh SP 3710DN/SF, desktop monocromatica. Baseie sua resposta nos TRECHOS DO MANUAL fornecidos e apresente TODAS as informacoes relevantes deles — nao resuma demais. Organize o diagnostico em: Defeito ou condicao, Possiveis causas, Solucao passo a passo e Pecas/ajustes quando houver. Pode acrescentar conhecimento tecnico adicional APENAS se for verdadeiro e diretamente relacionado, marcando como (Complemento). NUNCA invente codigos, valores de SP, tensoes, part numbers ou procedimentos que nao estejam nos trechos. Se os trechos nao trouxerem a solucao completa, apresente o que existe e informe que o restante deve ser consultado no service manual fisico. Portugues Brasileiro.',
    },
  },
];

// Todos os manuais juntos (para busca geral)
export const ALL_MANUALS = [...MANUALS, ...MANUALS_E826, ...MANUALS_RICOH];

// ─── MODEL_GROUPS (tela de Manuais) ───────────────────────────────────────────

export const BRAND_GROUPS = [
  {
    id: 'hp',
    label: 'HP',
    subtitle: 'HP LaserJet Managed',
    color: '#0096ff',
    icon: '🔵',
    models: [
      {
        id: 'mfpe52645_group',
        label: 'MFP E52645',
        subtitle: 'HP LaserJet Managed MFP E52645',
        color: '#0096ff',
        icon: '🖨️',
        manuals: [
          {
            id: 'guia',
            title: 'Guia do Usuario',
            subtitle: 'Manual de operacao PT-BR',
            desc: 'Operacao, configuracao e solucao de problemas',
            color: '#00d4aa',
            icon: '📗',
            tags: ['E52645', 'PT-BR', '6.5 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1AmQ0fExFjUBhVcK6yrEAjKNQJrYtRZLH&export=download&confirm=t',
            localName: 'tg_guia_e52645_v2.pdf',
            size: '6.5 MB',
          },
          {
            id: 'cpmd',
            title: 'Codigos de Erro (CPMD)',
            subtitle: 'Control Panel Message Document 2023',
            desc: 'Codigos de erro e procedimentos de solucao',
            color: '#a855f7',
            icon: '⚠️',
            tags: ['CPMD', '2023', '6.0 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1IwaqI0k8IycRTge9jy_1FX02JjjVbuuf&export=download&confirm=t',
            localName: 'tg_cpmd_2023_v2.pdf',
            size: '6.0 MB',
          },
          {
            id: 'service',
            title: 'Service Parts Catalog',
            subtitle: 'Catalogo de Pecas 2025',
            desc: 'Pecas, troubleshooting e procedimentos de reparo',
            color: '#0096ff',
            icon: '🔧',
            tags: ['Service', '2025', '90 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1ApI5qiLHTZaPKicn2SD5G6rqTrIFpPcQ&export=download&confirm=t',
            localName: 'tg_service_2025.pdf',
            size: '90 MB',
          },
        ],
      },
      {
        id: 'mfpe62655_group',
        label: 'MFP E62655',
        subtitle: 'HP LaserJet Managed MFP E62655',
        color: '#0096ff',
        icon: '🖨️',
        manuals: [
          {
            id: 'e62655_guia',
            title: 'Guia do Usuario',
            subtitle: 'Manual de operacao PT-BR',
            desc: 'Operacao, configuracao e solucao de problemas',
            color: '#00d4aa',
            icon: '📗',
            tags: ['E62655', 'PT-BR', '3.3 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1nReLfTlkWvTXU8JEdUNnkqrYZ_kNEdG8&export=download&confirm=t',
            localName: 'tg_guia_e62655.pdf',
            size: '3.3 MB',
          },
          {
            id: 'e62655_cpmd',
            title: 'Codigos de Erro (CPMD)',
            subtitle: 'Control Panel Message Document 2023',
            desc: 'Codigos de erro e procedimentos de solucao',
            color: '#a855f7',
            icon: '⚠️',
            tags: ['CPMD', '2023', '10 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1PKE-eD_-Ixk5vfC9ANb45nyDlHiJbcDf&export=download&confirm=t',
            localName: 'tg_cpmd_e62655.pdf',
            size: '10 MB',
          },
          {
            id: 'e62655_service',
            title: 'Service Parts Catalog',
            subtitle: 'Manual de servico e catalogo de pecas 2022',
            desc: 'Pecas, troubleshooting e procedimentos de reparo',
            color: '#0096ff',
            icon: '🔧',
            tags: ['Service', '2022', '71 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1hg-Ji4DNHCQXu2y1w5pO9cOj3oD-NsaJ&export=download&confirm=t',
            localName: 'tg_service_e62655.pdf',
            size: '71 MB',
          },
        ],
      },
      {
        id: 'hp_e826_group',
        label: 'E826 Series',
        subtitle: 'HP LaserJet Managed MFP E82650 / E82660 / E82670',
        color: '#0096ff',
        icon: 'ðŸ–¨ï¸',
        manuals: [
          {
            id: 'hp_e826_guia',
            title: 'Guia do Usuario',
            subtitle: 'Manual de operacao E826 Series',
            desc: 'Operacao, configuracao e solucao de problemas',
            color: '#00d4aa',
            icon: 'ðŸ“—',
            tags: ['E82650', 'E82660', 'E82670', '8.3 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1T6jWaRzZ2c-Rqxwl0naHSPXG-u27y_aj&export=download&confirm=t',
            localName: 'tg_guia_hp_e826.pdf',
            size: '8.3 MB',
          },
          {
            id: 'hp_e826_service',
            title: 'Service Manual + Parts Catalog',
            subtitle: 'Manual de servico e catalogo de pecas E826 Series',
            desc: 'Pecas, troubleshooting e procedimentos de reparo',
            color: '#0096ff',
            icon: 'ðŸ”§',
            tags: ['Service', 'Parts Catalog', 'E826', '140 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1hMzpRhjfF8Omei0gLZTFujwpoOW6LLAJ&export=download&confirm=t',
            localName: 'tg_service_parts_hp_e826.pdf',
            size: '140 MB',
          },
          {
            id: 'hp_e826_cpmd',
            title: 'Codigos de Erro (CPMD)',
            subtitle: 'Control Panel Messages Document E826 Series',
            desc: 'Codigos de erro e procedimentos de solucao - sera indexado na Camada 2',
            color: '#a855f7',
            icon: 'âš ï¸',
            tags: ['CPMD', 'E826', '43 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1zvkbys7ZODegZhkUkJmSwobfUUwIMP_Y&export=download&confirm=t',
            localName: 'tg_cpmd_hp_e826.pdf',
            size: '43 MB',
          },
        ],
      },
    ],
  },
  {
    id: 'ricoh',
    label: 'Ricoh',
    subtitle: 'Ricoh',
    color: '#e63946',
    icon: '🔴',
    models: [
      {
        id: 'ricoh_imc3000_group',
        label: 'IM C3000 / C3500',
        subtitle: 'Ricoh IM C3000 / IM C3500',
        color: '#e63946',
        icon: '🖨️',
        manuals: [
          // ← Links serão preenchidos depois do upload no Drive
          {
            id: 'ricoh_guia',
            title: 'Guia do Usuario',
            subtitle: 'Manual de operacao IM C3000/3500',
            desc: 'Operacao, configuracao e solucao de problemas',
            color: '#e63946',
            icon: '📕',
            tags: ['IM C3000', 'IM C3500', '48 MB'],
            url: 'https://drive.usercontent.google.com/download?id=11O2zD-BCQq71GgJ85qtwLGV-39ryoBfk&export=download&confirm=t',
            localName: 'tg_ricoh_guia_imc3000.pdf',
            size: '48 MB',
          },
          {
            id: 'ricoh_service',
            title: 'Service Manual',
            subtitle: 'Manual de servico tecnico',
            desc: 'Procedimentos de reparo, ajustes e diagnostico',
            color: '#ff6b35',
            icon: '🔧',
            tags: ['Service', 'IM C3000', '84 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1Lhct-qSmKYMV6wneIr6MW3bP8v5TMAwE&export=download&confirm=t',
            localName: 'tg_ricoh_service_imc3000.pdf',
            size: '84 MB',
          },
          {
            id: 'ricoh_parts',
            title: 'Product Support Guide',
            subtitle: 'Vida util das pecas de desgaste natural',
            desc: 'Part numbers, pecas e diagramas de montagem',
            color: '#f59e0b',
            icon: '📋',
            tags: ['Parts', 'IM C3500', '0.9 MB'],
            url: 'https://drive.usercontent.google.com/download?id=128-etdw8eLoJkaV-dSzA8QHFibJ0zp1b&export=download&confirm=t',
            localName: 'tg_ricoh_parts_imc3000.pdf',
            size: '0.9 MB',
          },
          {
            // Somente consulta (download) — nao entra na busca do chat (searchKeys/indice)
            id: 'ricoh_parts_catalog',
            title: 'Parts Catalog',
            subtitle: 'Catálogo completo de peças',
            desc: 'Part numbers e diagramas de montagem — somente consulta',
            color: '#f59e0b',
            icon: '📦',
            tags: ['Parts Catalog', 'IM C3000', '12 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1lFgxlL_E4ul4EGzTR_dY5x9rRUpwsrWd&export=download&confirm=t',
            localName: 'tg_ricoh_parts_catalog_imc3000.pdf',
            size: '12 MB',
          },
        ],
      },
      {
        id: 'ricoh_mpc3004_group',
        label: 'MP C3004/3504',
        subtitle: 'Ricoh MP C3004 / C3504 / C4504',
        color: '#e63946',
        icon: '🖨️',
        manuals: [
          {
            id: 'ricoh_mpc3004_guia',
            title: 'Guia do Usuario',
            subtitle: 'Manual de operacao MP C3004/3504/4504',
            desc: 'Operacao, configuracao e solucao de problemas',
            color: '#e63946',
            icon: '📕',
            tags: ['Guia', 'MP C3004', 'MP C3504', '7 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1NbV4S5IIX5e8wX4spY2TciXzfhdYy-rC&export=download&confirm=t',
            localName: 'tg_ricoh_guia_mpc3004.pdf',
            size: '7 MB',
          },
          {
            id: 'ricoh_mpc3004_service',
            title: 'Service Manual',
            subtitle: 'Manual de servico tecnico MP C3004/3504/4504',
            desc: 'Codigos SC, diagnostico, reparo e part numbers',
            color: '#ff6b35',
            icon: '🔧',
            tags: ['Service', 'MP C3004', 'MP C3504', '61 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1ylExuQ9rQJsi25u4VEhnSb1BG05l05QA&export=download&confirm=t',
            localName: 'tg_ricoh_service_mpc3004.pdf',
            size: '61 MB',
          },
          {
            // Somente consulta (download) — nao entra na busca do chat (searchKeys/indice)
            id: 'ricoh_mpc3004_parts_catalog',
            title: 'Parts Catalog',
            subtitle: 'Catalogo de pecas MP C3004/3504/4504 (2025)',
            desc: 'Part numbers e diagramas de montagem — somente consulta',
            color: '#f59e0b',
            icon: '📦',
            tags: ['Parts Catalog', 'MP C3004', 'MP C3504', '13 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1tTLSa-OZW_ykE2YR14Ed1RvoGc__FaOM&export=download&confirm=t',
            localName: 'tg_ricoh_parts_catalog_mpc3004.pdf',
            size: '13 MB',
          },
        ],
      },
      {
        id: 'ricoh_sp3710_group',
        label: 'SP 3710DN/SF',
        subtitle: 'Ricoh SP 3710 Series - Desktop Mono',
        color: '#e63946',
        icon: '🖨️',
        manuals: [
          {
            id: 'ricoh_sp3710_guia',
            title: 'Guia do Usuario',
            subtitle: 'Manual de operacao SP 3710DN/SF',
            desc: 'Operacao, configuracao e solucao de problemas',
            color: '#e63946',
            icon: '📕',
            tags: ['Guia', 'SP 3710DN', 'SP 3710SF', '5.6 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1Iu_GneoZmhtSf-v9P3pQpsafJm2tVks1&export=download&confirm=t',
            localName: 'tg_ricoh_guia_sp3710.pdf',
            size: '5.6 MB',
          },
          {
            id: 'ricoh_sp3710_service',
            title: 'Service Manual',
            subtitle: 'Manual de servico tecnico SP 3710DN/SF',
            desc: 'Diagnostico, reparo, ajustes e procedimentos de servico',
            color: '#ff6b35',
            icon: '🔧',
            tags: ['Service', 'SP 3710DN', 'SP 3710SF', '11.5 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1aNq74FQyNCwiHEUhi_Io45Dbdf8UsNpQ&export=download&confirm=t',
            localName: 'tg_ricoh_service_sp3710.pdf',
            size: '11.5 MB',
          },
          {
            id: 'ricoh_sp3710_psg',
            title: 'Product Support Guide',
            subtitle: 'Informacoes de produto e suporte da serie SP 3710',
            desc: 'Suprimentos, rendimento, instalacao e dados de suporte',
            color: '#f59e0b',
            icon: '📋',
            tags: ['Product Support', 'SP 3710', '0.6 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1JSD6dOuxOkXfdwe-N-RCctHkUU9FMWLD&export=download&confirm=t',
            localName: 'tg_ricoh_psg_sp3710.pdf',
            size: '0.6 MB',
          },
          {
            // Somente consulta (download) — nao entra na busca do chat (searchKeys/indice)
            id: 'ricoh_sp3710_parts_catalog',
            title: 'Parts Catalog',
            subtitle: 'Catalogo de pecas SP 3710SF',
            desc: 'Part numbers e diagramas de montagem — somente consulta',
            color: '#f59e0b',
            icon: '📦',
            tags: ['Parts Catalog', 'SP 3710SF', '3.5 MB'],
            url: 'https://drive.usercontent.google.com/download?id=1WKPcf516DCtk5JTWy4PEcxC0zS2UgY5L&export=download&confirm=t',
            localName: 'tg_ricoh_parts_catalog_sp3710.pdf',
            size: '3.5 MB',
          },
        ],
      },
    ],
  },
];

// Mantido para compatibilidade com ManualsScreen antigo (não usado mais)
export const MODEL_GROUPS = BRAND_GROUPS.flatMap(b => b.models);
